In [31]:
#a.Импортируйте библиотеку NumPy
import numpy as np


#b.Создайте массив из 10 нулей
a=np.zeros(10)
print(a)


#c.Создать массив из 10 единиц
c=np.ones(10)
print(c)


#d.Создать массив из 10 пятерок
d=np.ones(10)*5
print(d)




#e.Создать массив из целых чисел от 10 до 50
e=np.arange(10,51)
print(e)



#f.Создать массив из четных чисел от 10 до 50
f=np.arange(10,51,2)
print(f)


#g.Создать матрицу 3х3 с числами от 0 до 8
g=np.arange(9).reshape(3,3)
print(g)




#h.Создать единичную матрицу 3x3
h=np.eye(3)
print(h)


#i.Используйте NumPy для генерации случайного числа от 0 до 1
i=np.random.rand()
print(i)



#j.Используйте NumPy для генерации массива из 25 случайных чисел,взятых из стандартного нормального распределения
j=np.random.rand(25)
print(j)



#k.Создайте следующую матрицу используя функции библиотеки NumPy:l.Дана стартовая матрица (обязательно запустите код ниже в вашемрешении!). 
#Эта матрица будет использоваться в последующих задачах
# это наша стартовая матрица
mat = np.arange(1,26).reshape(5,5)
print(mat)

#Необходимо написать код который вернет следующую матрицу из стартовой:
print(mat[1:,1:])



#m.Написать код обращения к элементу который вернет значение  20 из стартовой матрицы задачи l.
print(mat[3,4])


#n.Написать код к стартовой матрице задачи l , который воспроизводит вывод, показанный ниже
print(mat[:3,1])

#o.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
print(mat[4:,:])

#p.Написать код к стартовой матрице задачи l , который воспроизводитвывод, показанный ниже
print(mat[3:,:])

#q.Получить сумму всех значений в стартовой матрице mat
print(mat.sum())

#r.Получить стандартное отклонение в стартовой матрице mat
print(mat.std())


#s.Получить сумму значений в колонках в стартовой матрице mat
print(mat.sum(axis=0))

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[5. 5. 5. 5. 5. 5. 5. 5. 5. 5.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]
[10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
0.8299197407325811
[0.42075409 0.73027601 0.93556514 0.36047002 0.10850266 0.39421896
 0.70967705 0.97601975 0.06774183 0.65006832 0.18117956 0.04936939
 0.43010497 0.42914859 0.55266301 0.71885006 0.92466292 0.44435099
 0.55608896 0.24250727 0.96323812 0.24868814 0.53753701 0.87976276
 0.88164609]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]
[[ 7  8  9 10]
 [12 13 14 15]
 [17 18 19 20]
 [22 23 24 25]]
20
[ 2  7 12]
[[21 22 23 24 25]]
[[16 17 18 19 20]
 [21 22 23 24 25]]
325
7.211102550927978
[55 60 65 70 75]
